### ISSUE TITLE
配置文件不会正常生成

### ISSUE THREAD

**Issue by chu025** [MCTeamPotato/MCMOD#3]
![image](https://github.com/MCTeamPotato/MCMOD/assets/129959496/25b84b4c-8249-4949-863e-8f105bd16907)
图中模组已正常运行，但是没有配置文件
![image](https://github.com/MCTeamPotato/MCMOD/assets/129959496/568ffbc6-72fb-4c6a-b61e-992b28fe132d)
这些放到一起会导致服务器无法正常进入（客户端一直协商，服务器显示玩家取消链接），还会导致服务器无法正常关闭
![image](https://github.com/MCTeamPotato/MCMOD/assets/129959496/f7a1313a-28a5-4606-9203-876254882ea4)
，导致重启脚本无法运作，但把该模组移除后一切正常，并且日志没有任何报错（无论是否移除）。

**Comment by AweiMC** [comment]
配置文件是这个，你有在仔细看了吗？
![image](https://github.com/MCTeamPotato/MCMOD/assets/122848147/6fc0be65-7f37-4b58-8442-643cfbb39dd4)

**Comment by chu025** [comment]
谢谢，但是服务器没法关咋整，下面的问题也帮我看看，拜托了

**Comment by chu025** [comment]
![捕获](https://github.com/MCTeamPotato/MCMOD/assets/129959496/9fa10351-5f03-42ff-a4c4-e9905e098050)

**Comment by chu025** [comment]
下面是文件，请帮我看看，拜托了，谢谢您https://7wcy1f-my.sharepoint.com/:u:/g/personal/chu015_7wcy1f_onmicrosoft_com/EaUDs-KOh_tFnnbgma7b34oBBu6antJINu8tZotVBIsxcg

**Comment by AweiMC** [comment]
你把MCMOd模组移除后再试一试

**Comment by chu025** [comment]
![image](https://github.com/MCTeamPotato/MCMOD/assets/129959496/1c7548f6-4699-43df-9c19-677b03b62327)

![image](https://github.com/MCTeamPotato/MCMOD/assets/129959496/662a78d1-ec9d-49eb-88b9-edeb33f3729e)
这样，您看可以吗？但它移除后好像能正常重启，打扰您了实在抱歉，谢谢您，拜托了。
